---
# tasks file for mysql
- name: Update repositories cache and install "gnupg" package
  apt:
    name: gnupg
    update_cache: yes


- name: Print Var
  debug:
    msg: Variable is {{ mysql_apt_config }}

- name: wget https://dev.mysql.com/get/{{ mysql_apt_config }}
  get_url:
    url: https://dev.mysql.com/get/{{ mysql_apt_config }}
    dest: /tmp/{{ mysql_apt_config }}
#    mode: '0440'

- name: Install a .deb package
  apt:
    deb: /tmp/{{ mysql_apt_config }}

- name: apt-get update
  apt:
    update_cache: yes


- name: Install mysql-server  
  apt:
    name: mysql-server
    state: present

#- name: Enable service mysql-server, and not touch the state
#  service:
#    name: mysql-server
#    enabled: yes