---
- name: Automatic backup Cisco Nexus
  hosts: servers
  gather_facts: false
  connection: local
  vars_files:
    - vars.yml

  tasks:
    - name: display the runnning config
      ios_command: 
        commands: 
         - show run
      register: config
    - name: save output to file
      copy:
        content: "{{ config.stdout[0] }}" 
        dest: "show_run_{{ inventory_hostname }}.cfg"


