---
#- name: Get IP
#  debug: msg={{ansible_default_ipv4}}
  
- name: Get Host
  debug: msg={{ansible_hostname}}  
  
- name: remove google.list
  shell: rm -rf /etc/apt/sources.list.d/go*  
  
- name: apt-get update
  apt:
    update_cache: yes
  
  
- name: apt-key add
  shell: wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
  
- name: Add the Google repository
  apt_repository: repo="deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" state="present"  

- name: apt-get install google-chrome-stable --only-upgrade
  # shell: sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list' && apt-get update && apt-get --only-upgrade install google-chrome-stable  
  apt:
    name: google-chrome-stable
    state: latest
#    only_upgrade: yes  
  
  
  
  
  