---
- hosts: all
  gather_facts: True
  #
  #become: yes
  #sudo: yes

  pre_tasks:
    - debug: msg="reading from {{env_name}}"


  roles:
      - cameras.alfa-server
    

  post_tasks:
   - debug: msg="All done {{env_name}}"
   