---
- name: Test
  hosts: all
  become: yes
  
  roles:
     - { role: deploy_node_exporter, when: ansible_system == 'Linux' }
    
  
#  tasks:
#    - name: Ping Host
#      ping:
#      
#    - name: Check and print LINUX Version
#      debug: var=ansible_os_family
  
      