---
# tasks file for deploy_docker-compose
- name: Deploy docker-compose
  shell:
    cmd: curl -L "https://github.com/docker/compose/releases/download/1.26.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    
- name: chmod +x /usr/local/bin/docker-compose
  file:
    path: /usr/local/bin/docker-compose
    mode: +x
        
