---
# tasks file for deploy_node_exporter
#- name: wget https://github.com/prometheus/node_exporter/releases/download/v1.0.0/node_exporter-1.0.0.linux-amd64.tar.gz
#  get_url:
#    url: https://github.com/prometheus/node_exporter/releases/download/v1.0.0/node_exporter-1.0.0.linux-amd64.tar.gz
#    dest: /root/node_exporter-1.0.0.linux-amd64.tar.gz


- name: Extract node_exporter-*.tar.gz into root dir
  unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v1.0.0/node_exporter-1.0.0.linux-amd64.tar.gz
    dest: /root
    remote_src: yes

- name: cp node_exporter /usr/local/bin
  shell: cp /root/node_exporter-1.0.0.linux-amd64/node_exporter /usr/local/bin/
  
- name: Add the system user 'node_exporter'
  user:
    name: node_exporter
    system: yes

- name: create  /etc/systemd/system/node_exporter.service file
  template: 
    src: node_exporter.service.j2
    dest: /etc/systemd/system/node_exporter.service
    

- name: Start and Enable Service node_exporter
  service:
    name: node_exporter
    state: started
    enabled: yes
         
    
      


