- name: python manage.py migrate (django_manage ansible module )
  django_manage:
    command: migrate
    app_path: "/home/startell/startell"

- name: createsuperuser
  django_manage:
    command: shell -c "from django.contrib.auth import get_user_model; User=get_user_model(); User.objects.count()==0 or exit(); user=User.objects.create_user('{{ django_default_user_name }}', password='{{ django_default_user_password }}'); user.is_superuser=True; user.is_staff=True;user.save()"
    app_path: "/home/startell/startell"
    
  