---
- hosts: servers #can be all
  vars:
#    - vhost: 91.201.240.129
#    - var1: hello
  vars_files:
    - vault/secrets.yml    
  remote_user: ivanov
  become: yes
  gather_facts: True

  pre_tasks:
    - name: Updating yum cache
      yum:
         name: "*"
         update_cache: yes
      when: ansible_os_family == "RedHat"
      
  roles:
    - role: googlechromeupdate
#    - role: getsystemrelease
    
    