- name: install mysql
  apt: package={{item}} state=present
  when: ansible_os_family == 'Debian'
  with_items:
     - mysql-server
     - python-mysqldb
     
- name: Create a new database with name 'vncbd'
  mysql_db:
     name: vncbd
     state: present
     
- name: Create a MySQL user vnc with password
  mysql_user:
    name: vncadmin
    password: 7xn06ej5k8
    priv: '*.*:ALL' 
    state: present
