---
#- name: Install common-packages
#  packages: "name={{ item }} state=installed"
#  with_items: "{{ common_packages }}"
- name: apt get install
  apt: name={{ item }} state=present
  with_items: "{{ common_packages }}"
  tags: [apt]  