---
- hosts: all
  gather_facts: False
  become: yes
  #sudo: yes

  pre_tasks:
    - debug: msg="reading from {{env_name}}"


  roles:
      - users
    # - webserver
    # - mailserver

  post_tasks:
   - debug: msg="All done {{env_name}}"



