---
# tasks file for deploy_docker

- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
    
- name: "Install a list of packages: apt-transport-https, ca-certificates, curl, gnupg-agent, software-properties-common"
  apt:
    pkg:
    - apt-transport-https
    - ca-certificates
    - curl
    - gnupg-agent
    - software-properties-common
    
    
- name: Add an Apt signing key, uses whichever key is at the URL
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present    
    
- name: Add the Docker repository
  #shell: "sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'"
  apt_repository: repo="deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable" state="present"    
  
  
- name: Update repositories cache and install  docker-ce docker-ce-cli containerd.io  packages
  apt:
    pkg:
     - docker-ce
     - docker-ce-cli
     - containerd.io 
      
    update_cache: yes  