---

- name: Extract blackbox_exporter-*.tar.gz into root dir
  unarchive:
    src: https://github.com/prometheus/blackbox_exporter/releases/download/v0.16.0/blackbox_exporter-0.16.0.linux-amd64.tar.gz
    dest: /root
    remote_src: yes

- name: cp blackbox_exporter /usr/local/bin
  shell: cp /root/blackbox_exporter-0.16.0.linux-amd64/blackbox_exporter /usr/local/bin/
  
- name: create dir /etc/blackbox_exporter
  file:
    path: /etc/blackbox_exporter
    state: directory
    mode: '0755'

  
- name: cp blackbox.yml /etc/blackbox_exporter
  shell: cp /root/blackbox_exporter-0.16.0.linux-amd64/blackbox.yml /etc/blackbox.yml
    
  
- name: Add the system user 'blackbox_exporter'
  user:
    name: blackbox_exporter
    system: yes

- name: create  /etc/systemd/system/blackbox_exporter.service file
  template: 
    src: blackbox_exporter.service.j2
    dest: /etc/systemd/system/blackbox_exporter.service
    

- name: Start and Enable Service blackbox_exporter
  service:
    name: blackbox_exporter
    state: started
    enabled: yes
